QUESTION_PER_LESSON: 5

size:
  width: "100%"
  height: "100%"
type:
  image: "image"
avatar:
  size: 50
  width: "100"
  height: "100"
  mini_size: 10
  size_img_tag: "20"
  default: "default.jpg"
per_page: 5

activities:
  learned: "Learned"
users:
  per_page: 5
option:
  - learned
  - unlearned
  - all
relationships: ["followers", "following"]
email_subject: "You have new result"
